-- Gestão de Lojas: CNPJ da loja e controle das mensalidades cobradas pela plataforma.

-- 1) CNPJ (só dígitos) e configuração padrão da mensalidade
ALTER TABLE s_loja ADD COLUMN IF NOT EXISTS cnpj varchar(18);
ALTER TABLE s_loja ADD COLUMN IF NOT EXISTS valor_mensalidade numeric(38, 2) NOT NULL DEFAULT 0;
ALTER TABLE s_loja ADD COLUMN IF NOT EXISTS dia_vencimento integer;

ALTER TABLE s_loja DROP CONSTRAINT IF EXISTS ck_s_loja_dia_vencimento;
ALTER TABLE s_loja ADD CONSTRAINT ck_s_loja_dia_vencimento
    CHECK (dia_vencimento IS NULL OR dia_vencimento BETWEEN 1 AND 28);

CREATE UNIQUE INDEX IF NOT EXISTS uk_s_loja_cnpj ON s_loja (cnpj) WHERE cnpj IS NOT NULL AND deletado = false;

-- 2) Mensalidades: uma por loja e competência (mês). PENDENTE vencida é exibida como "atrasada".
CREATE TABLE IF NOT EXISTS s_loja_mensalidade (
    id_loja_mensalidade bigint GENERATED BY DEFAULT AS IDENTITY,
    ativo               boolean        NOT NULL DEFAULT true,
    deletado            boolean        NOT NULL DEFAULT false,
    guid                uuid           NOT NULL,
    id_loja             bigint         NOT NULL,
    competencia         date           NOT NULL,
    valor               numeric(38, 2) NOT NULL,
    data_vencimento     date           NOT NULL,
    data_pagamento      date,
    situacao            varchar(255)   NOT NULL,
    observacao          varchar(2000),
    CONSTRAINT pk_s_loja_mensalidade PRIMARY KEY (id_loja_mensalidade),
    CONSTRAINT uk_s_loja_mensalidade_guid UNIQUE (guid),
    CONSTRAINT fk_s_loja_mensalidade_loja FOREIGN KEY (id_loja) REFERENCES s_loja (id_loja),
    CONSTRAINT ck_s_loja_mensalidade_situacao CHECK (situacao IN ('PENDENTE', 'PAGA', 'CANCELADA'))
);

CREATE INDEX IF NOT EXISTS ix_s_loja_mensalidade_loja ON s_loja_mensalidade (id_loja);
-- uma mensalidade por mês em cada loja (as excluídas não contam)
CREATE UNIQUE INDEX IF NOT EXISTS uk_s_loja_mensalidade_competencia
    ON s_loja_mensalidade (id_loja, competencia) WHERE deletado = false;
