-- Contatos da loja (telefones e e-mails), cadastrados na Gestão de Lojas. O primeiro telefone continua
-- sendo copiado para s_loja.telefone, que o cardápio público exibe.

CREATE TABLE IF NOT EXISTS s_loja_telefone (
    id_loja_telefone bigint GENERATED BY DEFAULT AS IDENTITY,
    ativo            boolean      NOT NULL DEFAULT true,
    deletado         boolean      NOT NULL DEFAULT false,
    guid             uuid         NOT NULL,
    id_loja          bigint       NOT NULL,
    tipo             varchar(255) NOT NULL,
    numero           varchar(20)  NOT NULL,
    observacao       varchar(255),
    CONSTRAINT pk_s_loja_telefone PRIMARY KEY (id_loja_telefone),
    CONSTRAINT uk_s_loja_telefone_guid UNIQUE (guid),
    CONSTRAINT fk_s_loja_telefone_loja FOREIGN KEY (id_loja) REFERENCES s_loja (id_loja),
    CONSTRAINT ck_s_loja_telefone_tipo CHECK (tipo IN ('COMERCIAL', 'RESIDENCIAL', 'CELULAR', 'OUTRO'))
);

CREATE INDEX IF NOT EXISTS ix_s_loja_telefone_loja ON s_loja_telefone (id_loja);

CREATE TABLE IF NOT EXISTS s_loja_email (
    id_loja_email bigint GENERATED BY DEFAULT AS IDENTITY,
    ativo         boolean      NOT NULL DEFAULT true,
    deletado      boolean      NOT NULL DEFAULT false,
    guid          uuid         NOT NULL,
    id_loja       bigint       NOT NULL,
    email         varchar(255) NOT NULL,
    observacao    varchar(255),
    CONSTRAINT pk_s_loja_email PRIMARY KEY (id_loja_email),
    CONSTRAINT uk_s_loja_email_guid UNIQUE (guid),
    CONSTRAINT fk_s_loja_email_loja FOREIGN KEY (id_loja) REFERENCES s_loja (id_loja)
);

CREATE INDEX IF NOT EXISTS ix_s_loja_email_loja ON s_loja_email (id_loja);

-- o telefone que já existia em s_loja vira o primeiro contato (lojas que ainda não têm nenhum)
INSERT INTO s_loja_telefone (guid, id_loja, tipo, numero)
SELECT gen_random_uuid(), l.id_loja, 'COMERCIAL', left(l.telefone, 20)
FROM s_loja l
WHERE l.telefone IS NOT NULL AND l.telefone <> ''
  AND NOT EXISTS (SELECT 1 FROM s_loja_telefone t WHERE t.id_loja = l.id_loja);
