-- Anotações internas sobre cada loja, escritas pela equipe da plataforma na Gestão de Lojas.
CREATE TABLE IF NOT EXISTS s_loja_anotacao (
    id_loja_anotacao bigint GENERATED BY DEFAULT AS IDENTITY,
    ativo            boolean       NOT NULL DEFAULT true,
    deletado         boolean       NOT NULL DEFAULT false,
    guid             uuid          NOT NULL,
    id_loja          bigint        NOT NULL,
    id_usuario       bigint        NOT NULL,
    texto            varchar(4000) NOT NULL,
    data_criacao     timestamp(0)  NOT NULL,
    data_alteracao   timestamp(0),
    CONSTRAINT pk_s_loja_anotacao PRIMARY KEY (id_loja_anotacao),
    CONSTRAINT uk_s_loja_anotacao_guid UNIQUE (guid),
    CONSTRAINT fk_s_loja_anotacao_loja FOREIGN KEY (id_loja) REFERENCES s_loja (id_loja),
    CONSTRAINT fk_s_loja_anotacao_usuario FOREIGN KEY (id_usuario) REFERENCES s_usuario (id_usuario)
);

CREATE INDEX IF NOT EXISTS ix_s_loja_anotacao_loja ON s_loja_anotacao (id_loja);
