-- Preferências de tela de cada usuário (ex.: posição dos widgets e período escolhido nos dashboards).
-- São do usuário logado e o acompanham em qualquer navegador; um usuário nunca enxerga as de outro.
CREATE TABLE IF NOT EXISTS s_usuario_preferencia (
    id_usuario_preferencia bigint GENERATED BY DEFAULT AS IDENTITY,
    ativo                  boolean      NOT NULL DEFAULT true,
    deletado               boolean      NOT NULL DEFAULT false,
    guid                   uuid         NOT NULL,
    id_usuario             bigint       NOT NULL,
    chave                  varchar(80)  NOT NULL,
    valor                  text         NOT NULL,
    CONSTRAINT pk_s_usuario_preferencia PRIMARY KEY (id_usuario_preferencia),
    CONSTRAINT uk_s_usuario_preferencia_guid UNIQUE (guid),
    CONSTRAINT uk_s_usuario_preferencia_usuario_chave UNIQUE (id_usuario, chave),
    CONSTRAINT fk_s_usuario_preferencia_usuario FOREIGN KEY (id_usuario) REFERENCES s_usuario (id_usuario)
);
