-- Tabelas de sistema (s_): nivel plataforma, sem coluna tenant.

CREATE TABLE IF NOT EXISTS s_perfil (
    id_perfil bigint GENERATED BY DEFAULT AS IDENTITY,
    ativo     boolean      NOT NULL DEFAULT true,
    deletado  boolean      NOT NULL DEFAULT false,
    guid      uuid         NOT NULL,
    nome      varchar(255) NOT NULL,
    codigo    varchar(255) NOT NULL,
    CONSTRAINT pk_s_perfil PRIMARY KEY (id_perfil),
    CONSTRAINT uk_s_perfil_guid UNIQUE (guid),
    CONSTRAINT uk_s_perfil_codigo UNIQUE (codigo)
);

CREATE TABLE IF NOT EXISTS s_loja (
    id_loja                    bigint GENERATED BY DEFAULT AS IDENTITY,
    ativo                      boolean          NOT NULL DEFAULT true,
    deletado                   boolean          NOT NULL DEFAULT false,
    guid                       uuid             NOT NULL,
    nome                       varchar(255)     NOT NULL,
    situacao_conta             varchar(255)     NOT NULL,
    tipo_organizacao           varchar(255)     NOT NULL,
    slug                       varchar(255)     NOT NULL,
    descricao                  varchar(255),
    telefone                   varchar(255),
    logo_url                   varchar(255),
    endereco_rua               varchar(255),
    endereco_numero            varchar(255),
    endereco_bairro            varchar(255),
    endereco_cidade            varchar(255),
    endereco_estado            varchar(255),
    endereco_cep               varchar(255),
    latitude                   double precision,
    longitude                  double precision,
    taxa_entrega_base          numeric(38, 2)   NOT NULL DEFAULT 0,
    taxa_entrega_por_km        numeric(38, 2)   NOT NULL DEFAULT 0,
    distancia_maxima_entrega_km double precision,
    valor_minimo_pedido        numeric(38, 2)   NOT NULL DEFAULT 0,
    CONSTRAINT pk_s_loja PRIMARY KEY (id_loja),
    CONSTRAINT uk_s_loja_guid UNIQUE (guid),
    CONSTRAINT uk_s_loja_slug UNIQUE (slug),
    CONSTRAINT ck_s_loja_situacao_conta CHECK (situacao_conta IN
        ('TRIAL', 'ATIVA', 'INADIMPLENTE', 'BLOQUEADA', 'CANCELADA')),
    CONSTRAINT ck_s_loja_tipo_organizacao CHECK (tipo_organizacao IN
        ('RESTAURANTE', 'LANCHONETE', 'PIZZARIA', 'CAFETERIA', 'CONFEITARIA', 'OUTRO'))
);

-- O vinculo do usuario com as lojas fica em t_perfil_usuario.
-- Usuario de suporte sem nenhum perfil vinculado e "usuario do sistema" e ve todas as lojas.
CREATE TABLE IF NOT EXISTS s_usuario (
    id_usuario          bigint GENERATED BY DEFAULT AS IDENTITY,
    ativo               boolean      NOT NULL DEFAULT true,
    deletado            boolean      NOT NULL DEFAULT false,
    guid                uuid         NOT NULL,
    nome                varchar(255) NOT NULL,
    email               varchar(255) NOT NULL,
    senha               varchar(255) NOT NULL,
    usuario_suporte     boolean      NOT NULL DEFAULT false,
    exige_trocar_senha  boolean      NOT NULL DEFAULT false,
    esqueci_senha_token varchar(255),
    data_criacao        timestamp(0) NOT NULL,
    data_ultimo_acesso  timestamp(0),
    CONSTRAINT pk_s_usuario PRIMARY KEY (id_usuario),
    CONSTRAINT uk_s_usuario_guid UNIQUE (guid),
    CONSTRAINT uk_s_usuario_email UNIQUE (email)
);

CREATE TABLE IF NOT EXISTS s_categoria_menu (
    id_categoria_menu bigint GENERATED BY DEFAULT AS IDENTITY,
    ativo             boolean      NOT NULL DEFAULT true,
    deletado          boolean      NOT NULL DEFAULT false,
    guid              uuid         NOT NULL,
    nome              varchar(255) NOT NULL,
    icone             varchar(255) NOT NULL,
    ordem             integer      NOT NULL DEFAULT 0,
    CONSTRAINT pk_s_categoria_menu PRIMARY KEY (id_categoria_menu),
    CONSTRAINT uk_s_categoria_menu_guid UNIQUE (guid)
);

CREATE TABLE IF NOT EXISTS s_pagina (
    id_pagina         bigint GENERATED BY DEFAULT AS IDENTITY,
    ativo             boolean      NOT NULL DEFAULT true,
    deletado          boolean      NOT NULL DEFAULT false,
    guid              uuid         NOT NULL,
    id_categoria_menu bigint       NOT NULL,
    nome              varchar(255) NOT NULL,
    rota              varchar(255) NOT NULL,
    ordem             integer      NOT NULL DEFAULT 0,
    CONSTRAINT pk_s_pagina PRIMARY KEY (id_pagina),
    CONSTRAINT uk_s_pagina_guid UNIQUE (guid),
    CONSTRAINT fk_s_pagina_categoria_menu FOREIGN KEY (id_categoria_menu) REFERENCES s_categoria_menu (id_categoria_menu)
);

CREATE INDEX IF NOT EXISTS ix_s_pagina_categoria_menu ON s_pagina (id_categoria_menu);
