-- Cadastro de produtos com 2 tipos: produto final (vendido no cardápio) e ingrediente (insumo).
-- O produto final tem uma composição (ficha técnica) feita de ingredientes.

-- 1) t_produto passa a guardar os dois tipos (os produtos que já existem são finais)
ALTER TABLE t_produto ADD COLUMN IF NOT EXISTS tipo           varchar(20)    NOT NULL DEFAULT 'FINAL';
ALTER TABLE t_produto ADD COLUMN IF NOT EXISTS codigo         varchar(50);
ALTER TABLE t_produto ADD COLUMN IF NOT EXISTS unidade_medida varchar(20)    NOT NULL DEFAULT 'UN';
ALTER TABLE t_produto ADD COLUMN IF NOT EXISTS custo_unitario numeric(38, 4) NOT NULL DEFAULT 0;
ALTER TABLE t_produto ADD COLUMN IF NOT EXISTS id_fornecedor  bigint;
ALTER TABLE t_produto ADD COLUMN IF NOT EXISTS observacao     varchar(2000);

-- ingrediente não tem categoria do cardápio nem preço de venda
ALTER TABLE t_produto ALTER COLUMN id_categoria DROP NOT NULL;
ALTER TABLE t_produto ALTER COLUMN preco SET DEFAULT 0;

ALTER TABLE t_produto DROP CONSTRAINT IF EXISTS ck_t_produto_tipo;
ALTER TABLE t_produto ADD CONSTRAINT ck_t_produto_tipo CHECK (tipo IN ('FINAL', 'INGREDIENTE'));
ALTER TABLE t_produto DROP CONSTRAINT IF EXISTS ck_t_produto_unidade_medida;
ALTER TABLE t_produto ADD CONSTRAINT ck_t_produto_unidade_medida
    CHECK (unidade_medida IN ('UN', 'KG', 'G', 'L', 'ML', 'PORCAO'));
-- produto final sempre pertence a uma categoria do cardápio
ALTER TABLE t_produto DROP CONSTRAINT IF EXISTS ck_t_produto_final_categoria;
ALTER TABLE t_produto ADD CONSTRAINT ck_t_produto_final_categoria
    CHECK (tipo <> 'FINAL' OR id_categoria IS NOT NULL);

ALTER TABLE t_produto DROP CONSTRAINT IF EXISTS fk_t_produto_fornecedor;
ALTER TABLE t_produto ADD CONSTRAINT fk_t_produto_fornecedor FOREIGN KEY (id_fornecedor) REFERENCES t_pessoa (id_pessoa);

-- um código por loja (o das excluídas não conta)
CREATE UNIQUE INDEX IF NOT EXISTS uk_t_produto_tenant_codigo
    ON t_produto (tenant, codigo) WHERE codigo IS NOT NULL AND deletado = false;
CREATE INDEX IF NOT EXISTS ix_t_produto_tipo ON t_produto (tenant, tipo);

-- 2) Composição: quanto de cada ingrediente entra em um produto final
CREATE TABLE IF NOT EXISTS t_produto_ingrediente (
    id_produto_ingrediente bigint GENERATED BY DEFAULT AS IDENTITY,
    ativo                  boolean        NOT NULL DEFAULT true,
    deletado               boolean        NOT NULL DEFAULT false,
    guid                   uuid           NOT NULL,
    tenant                 uuid,
    id_produto             bigint         NOT NULL,
    id_ingrediente         bigint         NOT NULL,
    quantidade             numeric(14, 3) NOT NULL,
    CONSTRAINT pk_t_produto_ingrediente PRIMARY KEY (id_produto_ingrediente),
    CONSTRAINT uk_t_produto_ingrediente_guid UNIQUE (guid),
    CONSTRAINT fk_t_produto_ingrediente_produto FOREIGN KEY (id_produto) REFERENCES t_produto (id_produto),
    CONSTRAINT fk_t_produto_ingrediente_ingrediente FOREIGN KEY (id_ingrediente) REFERENCES t_produto (id_produto),
    CONSTRAINT ck_t_produto_ingrediente_quantidade CHECK (quantidade > 0)
);

CREATE INDEX IF NOT EXISTS ix_t_produto_ingrediente_produto ON t_produto_ingrediente (id_produto);
CREATE INDEX IF NOT EXISTS ix_t_produto_ingrediente_ingrediente ON t_produto_ingrediente (id_ingrediente);

-- 3) Menu: Geral > Produtos > (Produtos finais, Ingredientes)
INSERT INTO s_pagina (guid, id_categoria_menu, nome, rota, ordem, screen)
SELECT gen_random_uuid(), c.id_categoria_menu, 'Produtos', NULL, 3, 'Geral, Produtos'
FROM s_categoria_menu c
WHERE c.nome = 'Geral'
  AND NOT EXISTS (SELECT 1 FROM s_pagina x WHERE x.id_categoria_menu = c.id_categoria_menu AND x.nome = 'Produtos' AND x.rota IS NULL);

INSERT INTO s_pagina (guid, id_categoria_menu, nome, rota, ordem, id_pagina_pai, screen)
SELECT gen_random_uuid(), p.id_categoria_menu, 'Produtos finais', '/admin/produtos-finais', 1, p.id_pagina,
       'Geral, Produtos, Produtos finais'
FROM s_pagina p
JOIN s_categoria_menu c ON c.id_categoria_menu = p.id_categoria_menu AND c.nome = 'Geral'
WHERE p.nome = 'Produtos' AND p.rota IS NULL
  AND NOT EXISTS (SELECT 1 FROM s_pagina x WHERE x.rota = '/admin/produtos-finais');

INSERT INTO s_pagina (guid, id_categoria_menu, nome, rota, ordem, id_pagina_pai, screen)
SELECT gen_random_uuid(), p.id_categoria_menu, 'Ingredientes', '/admin/ingredientes', 2, p.id_pagina,
       'Geral, Produtos, Ingredientes'
FROM s_pagina p
JOIN s_categoria_menu c ON c.id_categoria_menu = p.id_categoria_menu AND c.nome = 'Geral'
WHERE p.nome = 'Produtos' AND p.rota IS NULL
  AND NOT EXISTS (SELECT 1 FROM s_pagina x WHERE x.rota = '/admin/ingredientes');
