-- Horário de funcionamento da loja e o modo (automático pelo horário, ou aberta/fechada à força).
-- "Minha loja" passa de Configurações para Geral.

ALTER TABLE s_loja ADD COLUMN IF NOT EXISTS modo_funcionamento varchar(20) NOT NULL DEFAULT 'AUTOMATICO';
ALTER TABLE s_loja ADD COLUMN IF NOT EXISTS fuso_horario       varchar(50) NOT NULL DEFAULT 'America/Sao_Paulo';

ALTER TABLE s_loja DROP CONSTRAINT IF EXISTS ck_s_loja_modo_funcionamento;
ALTER TABLE s_loja ADD CONSTRAINT ck_s_loja_modo_funcionamento
    CHECK (modo_funcionamento IN ('AUTOMATICO', 'ABERTA', 'FECHADA'));

-- Intervalos de funcionamento por dia da semana (1 = segunda ... 7 = domingo). Um dia pode ter mais de um
-- intervalo (ex.: almoço e jantar). Se "fecha" é menor ou igual a "abre", o intervalo termina no dia seguinte.
CREATE TABLE IF NOT EXISTS s_loja_horario (
    id_loja_horario bigint GENERATED BY DEFAULT AS IDENTITY,
    ativo           boolean  NOT NULL DEFAULT true,
    deletado        boolean  NOT NULL DEFAULT false,
    guid            uuid     NOT NULL,
    id_loja         bigint   NOT NULL,
    dia_semana      smallint NOT NULL,
    abre            time     NOT NULL,
    fecha           time     NOT NULL,
    CONSTRAINT pk_s_loja_horario PRIMARY KEY (id_loja_horario),
    CONSTRAINT uk_s_loja_horario_guid UNIQUE (guid),
    CONSTRAINT fk_s_loja_horario_loja FOREIGN KEY (id_loja) REFERENCES s_loja (id_loja),
    CONSTRAINT ck_s_loja_horario_dia CHECK (dia_semana BETWEEN 1 AND 7),
    CONSTRAINT ck_s_loja_horario_intervalo CHECK (abre <> fecha)
);

CREATE INDEX IF NOT EXISTS ix_s_loja_horario_loja ON s_loja_horario (id_loja);

-- Menu: Geral > Minha loja (a categoria Configurações fica sem páginas e sai do menu)
UPDATE s_pagina p
SET id_categoria_menu = geral.id_categoria_menu, id_pagina_pai = NULL, ordem = 9, screen = 'Geral, Minha loja'
FROM s_categoria_menu geral
WHERE geral.nome = 'Geral' AND p.rota = '/admin/loja';

UPDATE s_categoria_menu c
SET ativo = false
WHERE c.nome = 'Configurações'
  AND NOT EXISTS (SELECT 1 FROM s_pagina p WHERE p.id_categoria_menu = c.id_categoria_menu AND p.ativo = true AND p.deletado = false);
