-- Permissões por tela. s_permissao é o catálogo (cada página tem visualizar, editar e ações específicas);
-- t_permissao_usuario liga o usuário (o vínculo dele com a loja) às permissões que ele tem.
-- Quem tem o papel ROLE_SISTEMA (usuário do sistema) ou é administrador da loja tem acesso a tudo, sem linhas aqui.

CREATE TABLE IF NOT EXISTS s_permissao (
    id_permissao bigint GENERATED BY DEFAULT AS IDENTITY,
    ativo        boolean      NOT NULL DEFAULT true,
    deletado     boolean      NOT NULL DEFAULT false,
    guid         uuid         NOT NULL,
    codigo       varchar(80)  NOT NULL,
    nome         varchar(255) NOT NULL,
    tipo         varchar(20)  NOT NULL,
    id_pagina    bigint       NOT NULL,
    ordem        integer      NOT NULL DEFAULT 0,
    CONSTRAINT pk_s_permissao PRIMARY KEY (id_permissao),
    CONSTRAINT uk_s_permissao_guid UNIQUE (guid),
    CONSTRAINT uk_s_permissao_codigo UNIQUE (codigo),
    CONSTRAINT fk_s_permissao_pagina FOREIGN KEY (id_pagina) REFERENCES s_pagina (id_pagina),
    CONSTRAINT ck_s_permissao_tipo CHECK (tipo IN ('LEITURA', 'ESCRITA', 'ACAO'))
);

CREATE INDEX IF NOT EXISTS ix_s_permissao_pagina ON s_permissao (id_pagina);

CREATE TABLE IF NOT EXISTS t_permissao_usuario (
    id_permissao_usuario bigint GENERATED BY DEFAULT AS IDENTITY,
    ativo                boolean NOT NULL DEFAULT true,
    deletado             boolean NOT NULL DEFAULT false,
    guid                 uuid    NOT NULL,
    tenant               uuid,
    id_perfil_usuario    bigint  NOT NULL,
    id_permissao         bigint  NOT NULL,
    CONSTRAINT pk_t_permissao_usuario PRIMARY KEY (id_permissao_usuario),
    CONSTRAINT uk_t_permissao_usuario_guid UNIQUE (guid),
    CONSTRAINT uk_t_permissao_usuario_perfil_permissao UNIQUE (id_perfil_usuario, id_permissao),
    CONSTRAINT fk_t_permissao_usuario_perfil FOREIGN KEY (id_perfil_usuario) REFERENCES t_perfil_usuario (id_perfil_usuario),
    CONSTRAINT fk_t_permissao_usuario_permissao FOREIGN KEY (id_permissao) REFERENCES s_permissao (id_permissao)
);

CREATE INDEX IF NOT EXISTS ix_t_permissao_usuario_perfil ON t_permissao_usuario (id_perfil_usuario);

-- Catálogo (uma linha por permissão, ligada à página do menu pela rota)
INSERT INTO s_permissao (guid, codigo, nome, tipo, id_pagina, ordem)
SELECT gen_random_uuid(), v.codigo, v.nome, v.tipo, p.id_pagina, v.ordem
FROM (VALUES
    ('/admin/dashboard', 'DASHBOARD_LEITURA', 'Visualizar a visão geral', 'LEITURA', 1),
    ('/admin/pedidos', 'PEDIDOS_LEITURA', 'Visualizar os pedidos', 'LEITURA', 1),
    ('/admin/pedidos', 'PEDIDOS_ESCRITA', 'Editar os pedidos', 'ESCRITA', 2),
    ('/admin/pedidos', 'PEDIDOS_ALTERAR_STATUS', 'Avançar a situação do pedido', 'ACAO', 3),
    ('/admin/pedidos', 'PEDIDOS_CANCELAR', 'Cancelar pedido', 'ACAO', 4),
    ('/admin/usuarios', 'USUARIOS_LEITURA', 'Visualizar os usuários', 'LEITURA', 1),
    ('/admin/usuarios', 'USUARIOS_ESCRITA', 'Editar os usuários', 'ESCRITA', 2),
    ('/admin/usuarios', 'USUARIOS_INCLUIR', 'Cadastrar usuário', 'ACAO', 3),
    ('/admin/usuarios', 'USUARIOS_ALTERAR', 'Alterar usuário', 'ACAO', 4),
    ('/admin/usuarios', 'USUARIOS_EXCLUIR', 'Excluir usuário', 'ACAO', 5),
    ('/admin/usuarios', 'USUARIOS_INATIVAR', 'Ativar e inativar usuários', 'ACAO', 6),
    ('/admin/usuarios', 'USUARIOS_ALTERAR_EMAIL', 'Alterar o e-mail do usuário', 'ACAO', 7),
    ('/admin/usuarios', 'USUARIOS_REDEFINIR_SENHA', 'Redefinir a senha do usuário', 'ACAO', 8),
    ('/admin/funcionarios', 'FUNCIONARIOS_LEITURA', 'Visualizar os funcionários', 'LEITURA', 1),
    ('/admin/funcionarios', 'FUNCIONARIOS_ESCRITA', 'Editar os funcionários', 'ESCRITA', 2),
    ('/admin/funcionarios', 'FUNCIONARIOS_INCLUIR', 'Cadastrar funcionário', 'ACAO', 3),
    ('/admin/funcionarios', 'FUNCIONARIOS_ALTERAR', 'Alterar funcionário', 'ACAO', 4),
    ('/admin/funcionarios', 'FUNCIONARIOS_EXCLUIR', 'Excluir funcionário', 'ACAO', 5),
    ('/admin/pessoas', 'CLIENTES_FORNECEDORES_LEITURA', 'Visualizar clientes e fornecedores', 'LEITURA', 1),
    ('/admin/pessoas', 'CLIENTES_FORNECEDORES_ESCRITA', 'Editar clientes e fornecedores', 'ESCRITA', 2),
    ('/admin/pessoas', 'CLIENTES_FORNECEDORES_INCLUIR', 'Cadastrar cliente e fornecedor', 'ACAO', 3),
    ('/admin/pessoas', 'CLIENTES_FORNECEDORES_ALTERAR', 'Alterar cliente e fornecedor', 'ACAO', 4),
    ('/admin/pessoas', 'CLIENTES_FORNECEDORES_EXCLUIR', 'Excluir cliente e fornecedor', 'ACAO', 5),
    ('/admin/produtos-finais', 'PRODUTOS_FINAIS_LEITURA', 'Visualizar os produtos finais', 'LEITURA', 1),
    ('/admin/produtos-finais', 'PRODUTOS_FINAIS_ESCRITA', 'Editar os produtos finais', 'ESCRITA', 2),
    ('/admin/produtos-finais', 'PRODUTOS_FINAIS_INCLUIR', 'Cadastrar produto final', 'ACAO', 3),
    ('/admin/produtos-finais', 'PRODUTOS_FINAIS_ALTERAR', 'Alterar produto final', 'ACAO', 4),
    ('/admin/produtos-finais', 'PRODUTOS_FINAIS_EXCLUIR', 'Excluir produto final', 'ACAO', 5),
    ('/admin/produtos-finais', 'PRODUTOS_FINAIS_INATIVAR', 'Ativar e inativar produtos finais', 'ACAO', 6),
    ('/admin/ingredientes', 'INGREDIENTES_LEITURA', 'Visualizar os ingredientes', 'LEITURA', 1),
    ('/admin/ingredientes', 'INGREDIENTES_ESCRITA', 'Editar os ingredientes', 'ESCRITA', 2),
    ('/admin/ingredientes', 'INGREDIENTES_INCLUIR', 'Cadastrar ingrediente', 'ACAO', 3),
    ('/admin/ingredientes', 'INGREDIENTES_ALTERAR', 'Alterar ingrediente', 'ACAO', 4),
    ('/admin/ingredientes', 'INGREDIENTES_EXCLUIR', 'Excluir ingrediente', 'ACAO', 5),
    ('/admin/ingredientes', 'INGREDIENTES_INATIVAR', 'Ativar e inativar ingredientes', 'ACAO', 6),
    ('/admin/categorias', 'CATEGORIAS_LEITURA', 'Visualizar as categorias', 'LEITURA', 1),
    ('/admin/categorias', 'CATEGORIAS_ESCRITA', 'Editar as categorias', 'ESCRITA', 2),
    ('/admin/categorias', 'CATEGORIAS_INCLUIR', 'Cadastrar categoria', 'ACAO', 3),
    ('/admin/categorias', 'CATEGORIAS_ALTERAR', 'Alterar categoria', 'ACAO', 4),
    ('/admin/categorias', 'CATEGORIAS_EXCLUIR', 'Excluir categoria', 'ACAO', 5),
    ('/admin/categorias', 'CATEGORIAS_INATIVAR', 'Ativar e inativar categorias', 'ACAO', 6),
    ('/admin/zonas-entrega', 'ZONAS_ENTREGA_LEITURA', 'Visualizar as zonas de entrega', 'LEITURA', 1),
    ('/admin/zonas-entrega', 'ZONAS_ENTREGA_ESCRITA', 'Editar as zonas de entrega', 'ESCRITA', 2),
    ('/admin/zonas-entrega', 'ZONAS_ENTREGA_INCLUIR', 'Cadastrar zona de entrega', 'ACAO', 3),
    ('/admin/zonas-entrega', 'ZONAS_ENTREGA_ALTERAR', 'Alterar zona de entrega', 'ACAO', 4),
    ('/admin/zonas-entrega', 'ZONAS_ENTREGA_EXCLUIR', 'Excluir zona de entrega', 'ACAO', 5),
    ('/admin/zonas-entrega', 'ZONAS_ENTREGA_INATIVAR', 'Ativar e inativar zonas de entrega', 'ACAO', 6),
    ('/admin/loja', 'MINHA_LOJA_LEITURA', 'Visualizar os dados da loja', 'LEITURA', 1),
    ('/admin/loja', 'MINHA_LOJA_ESCRITA', 'Editar os dados da loja', 'ESCRITA', 2),
    ('/admin/loja', 'MINHA_LOJA_ALTERAR', 'Alterar dados e regras de entrega', 'ACAO', 3),
    ('/admin/loja', 'MINHA_LOJA_HORARIO', 'Alterar o horário de funcionamento e abrir ou fechar a loja', 'ACAO', 4)
) AS v (rota, codigo, nome, tipo, ordem)
JOIN s_pagina p ON p.rota = v.rota
WHERE NOT EXISTS (SELECT 1 FROM s_permissao x WHERE x.codigo = v.codigo);

-- O papel do usuário do sistema passa a se chamar ROLE_SISTEMA
UPDATE s_perfil SET codigo = 'ROLE_SISTEMA', nome = 'Sistema' WHERE codigo = 'ROLE_SUPER_ADMIN';

-- Para não tirar o acesso de quem já usa o sistema: os usuários de loja que não são administradores
-- (e que até agora podiam tudo) recebem todas as permissões. Depois é só ajustar no cadastro do usuário.
INSERT INTO t_permissao_usuario (guid, tenant, id_perfil_usuario, id_permissao)
SELECT gen_random_uuid(), pu.tenant, pu.id_perfil_usuario, pe.id_permissao
FROM t_perfil_usuario pu
CROSS JOIN s_permissao pe
WHERE pu.administrador = false AND pu.deletado = false
  AND NOT EXISTS (SELECT 1 FROM t_permissao_usuario x WHERE x.id_perfil_usuario = pu.id_perfil_usuario AND x.id_permissao = pe.id_permissao);
