-- Formas de pagamento cadastráveis da loja (com taxa e regras de uso).
CREATE TABLE IF NOT EXISTS t_forma_pagamento (
    id_forma_pagamento bigint GENERATED BY DEFAULT AS IDENTITY,
    ativo              boolean       NOT NULL DEFAULT true,
    deletado           boolean       NOT NULL DEFAULT false,
    guid               uuid          NOT NULL,
    tenant             uuid,
    nome               varchar(100)  NOT NULL,
    tipo               varchar(30)   NOT NULL,
    taxa_percentual    numeric(5, 2) NOT NULL DEFAULT 0,
    taxa_fixa          numeric(10, 2) NOT NULL DEFAULT 0,
    valor_minimo       numeric(10, 2),
    aceita_entrega     boolean       NOT NULL DEFAULT true,
    aceita_retirada    boolean       NOT NULL DEFAULT true,
    ordem              integer       NOT NULL DEFAULT 0,
    CONSTRAINT pk_t_forma_pagamento PRIMARY KEY (id_forma_pagamento),
    CONSTRAINT uk_t_forma_pagamento_guid UNIQUE (guid)
);

CREATE INDEX IF NOT EXISTS ix_t_forma_pagamento_tenant ON t_forma_pagamento (tenant);

-- Desconto do pedido (percentual ou valor fixo, dado pela loja ao lançar o pedido).
ALTER TABLE t_pedido ADD COLUMN IF NOT EXISTS desconto_tipo  varchar(20);
ALTER TABLE t_pedido ADD COLUMN IF NOT EXISTS desconto_valor numeric(10, 2);
ALTER TABLE t_pedido ADD COLUMN IF NOT EXISTS desconto       numeric(10, 2) NOT NULL DEFAULT 0;

-- Geral > Formas de pagamento
INSERT INTO s_pagina (guid, id_categoria_menu, nome, rota, ordem, screen)
SELECT gen_random_uuid(), c.id_categoria_menu, 'Formas de pagamento', '/admin/formas-pagamento', 4, 'Geral, Formas de pagamento'
FROM s_categoria_menu c
WHERE c.nome = 'Geral'
  AND NOT EXISTS (SELECT 1 FROM s_pagina x WHERE x.rota = '/admin/formas-pagamento');

INSERT INTO s_permissao (guid, codigo, nome, tipo, id_pagina, ordem)
SELECT gen_random_uuid(), v.codigo, v.nome, v.tipo, p.id_pagina, v.ordem
FROM (VALUES
    ('/admin/formas-pagamento', 'FORMAS_PAGAMENTO_LEITURA', 'Visualizar as formas de pagamento', 'LEITURA', 1),
    ('/admin/formas-pagamento', 'FORMAS_PAGAMENTO_ESCRITA', 'Editar as formas de pagamento', 'ESCRITA', 2),
    ('/admin/formas-pagamento', 'FORMAS_PAGAMENTO_INCLUIR', 'Cadastrar forma de pagamento', 'ACAO', 3),
    ('/admin/formas-pagamento', 'FORMAS_PAGAMENTO_ALTERAR', 'Alterar forma de pagamento', 'ACAO', 4),
    ('/admin/formas-pagamento', 'FORMAS_PAGAMENTO_EXCLUIR', 'Excluir forma de pagamento', 'ACAO', 5),
    ('/admin/formas-pagamento', 'FORMAS_PAGAMENTO_INATIVAR', 'Ativar e inativar formas de pagamento', 'ACAO', 6),
    ('/admin/pedidos', 'PEDIDOS_EXCLUIR', 'Excluir pedido', 'ACAO', 11),
    ('/admin/painel-pedidos', 'PAINEL_PEDIDOS_EXCLUIR', 'Excluir pedido pelo painel', 'ACAO', 11)
) AS v (rota, codigo, nome, tipo, ordem)
JOIN s_pagina p ON p.rota = v.rota
WHERE NOT EXISTS (SELECT 1 FROM s_permissao x WHERE x.codigo = v.codigo);

-- Quem já cancela pedidos pode excluí-los (para não tirar nada de ninguém).
INSERT INTO t_permissao_usuario (guid, tenant, id_perfil_usuario, id_permissao)
SELECT gen_random_uuid(), pu.tenant, pu.id_perfil_usuario, novo.id_permissao
FROM t_permissao_usuario pu
JOIN s_permissao atual ON atual.id_permissao = pu.id_permissao AND atual.codigo IN ('PEDIDOS_CANCELAR', 'PAINEL_PEDIDOS_CANCELAR')
JOIN s_permissao novo ON novo.codigo = replace(atual.codigo, 'CANCELAR', 'EXCLUIR')
WHERE NOT EXISTS (SELECT 1 FROM t_permissao_usuario x
                  WHERE x.id_perfil_usuario = pu.id_perfil_usuario AND x.id_permissao = novo.id_permissao);
