-- Tabelas de tenant (t_) e de ligacao (i_): pertencem a uma loja.
-- A coluna tenant guarda o guid da s_loja dona do registro.

CREATE TABLE t_pessoa_fisica (
    id_pessoa_fisica bigint GENERATED BY DEFAULT AS IDENTITY,
    ativo            boolean      NOT NULL DEFAULT true,
    deletado         boolean      NOT NULL DEFAULT false,
    guid             uuid         NOT NULL,
    tenant           uuid,
    nome             varchar(255) NOT NULL,
    apelido          varchar(255),
    cpf              varchar(14),
    data_nascimento  date,
    telefone         varchar(255),
    CONSTRAINT pk_t_pessoa_fisica PRIMARY KEY (id_pessoa_fisica),
    CONSTRAINT uk_t_pessoa_fisica_guid UNIQUE (guid)
);

CREATE TABLE t_pessoa_juridica (
    id_pessoa_juridica bigint GENERATED BY DEFAULT AS IDENTITY,
    ativo              boolean      NOT NULL DEFAULT true,
    deletado           boolean      NOT NULL DEFAULT false,
    guid               uuid         NOT NULL,
    tenant             uuid,
    razao_social       varchar(255) NOT NULL,
    nome_fantasia      varchar(255),
    cnpj               varchar(18),
    telefone           varchar(255),
    CONSTRAINT pk_t_pessoa_juridica PRIMARY KEY (id_pessoa_juridica),
    CONSTRAINT uk_t_pessoa_juridica_guid UNIQUE (guid)
);

CREATE TABLE t_pessoa (
    id_pessoa          bigint GENERATED BY DEFAULT AS IDENTITY,
    ativo              boolean NOT NULL DEFAULT true,
    deletado           boolean NOT NULL DEFAULT false,
    guid               uuid    NOT NULL,
    tenant             uuid,
    id_pessoa_fisica   bigint,
    id_pessoa_juridica bigint,
    CONSTRAINT pk_t_pessoa PRIMARY KEY (id_pessoa),
    CONSTRAINT uk_t_pessoa_guid UNIQUE (guid),
    CONSTRAINT uk_t_pessoa_pessoa_fisica UNIQUE (id_pessoa_fisica),
    CONSTRAINT uk_t_pessoa_pessoa_juridica UNIQUE (id_pessoa_juridica),
    CONSTRAINT fk_t_pessoa_pessoa_fisica FOREIGN KEY (id_pessoa_fisica) REFERENCES t_pessoa_fisica (id_pessoa_fisica),
    CONSTRAINT fk_t_pessoa_pessoa_juridica FOREIGN KEY (id_pessoa_juridica) REFERENCES t_pessoa_juridica (id_pessoa_juridica),
    -- uma pessoa e fisica OU juridica, nunca as duas
    CONSTRAINT ck_t_pessoa_tipo CHECK (num_nonnulls(id_pessoa_fisica, id_pessoa_juridica) = 1)
);

-- Vinculo do usuario com uma loja: quem ele e la (id_pessoa) e com qual papel (id_perfil).
-- Um usuario pode ter varios (um por loja).
CREATE TABLE t_perfil_usuario (
    id_perfil_usuario bigint GENERATED BY DEFAULT AS IDENTITY,
    ativo             boolean NOT NULL DEFAULT true,
    deletado          boolean NOT NULL DEFAULT false,
    guid              uuid    NOT NULL,
    tenant            uuid,
    id_usuario        bigint  NOT NULL,
    id_pessoa         bigint  NOT NULL,
    id_loja           bigint  NOT NULL,
    id_perfil         bigint  NOT NULL,
    CONSTRAINT pk_t_perfil_usuario PRIMARY KEY (id_perfil_usuario),
    CONSTRAINT uk_t_perfil_usuario_guid UNIQUE (guid),
    CONSTRAINT uk_t_perfil_usuario_usuario_loja UNIQUE (id_usuario, id_loja),
    CONSTRAINT fk_t_perfil_usuario_usuario FOREIGN KEY (id_usuario) REFERENCES s_usuario (id_usuario),
    CONSTRAINT fk_t_perfil_usuario_pessoa FOREIGN KEY (id_pessoa) REFERENCES t_pessoa (id_pessoa),
    CONSTRAINT fk_t_perfil_usuario_loja FOREIGN KEY (id_loja) REFERENCES s_loja (id_loja),
    CONSTRAINT fk_t_perfil_usuario_perfil FOREIGN KEY (id_perfil) REFERENCES s_perfil (id_perfil)
);

CREATE INDEX ix_t_perfil_usuario_loja ON t_perfil_usuario (id_loja);

CREATE TABLE t_categoria (
    id_categoria   bigint GENERATED BY DEFAULT AS IDENTITY,
    ativo          boolean      NOT NULL DEFAULT true,
    deletado       boolean      NOT NULL DEFAULT false,
    guid           uuid         NOT NULL,
    tenant         uuid,
    nome           varchar(255) NOT NULL,
    ordem_exibicao integer,
    CONSTRAINT pk_t_categoria PRIMARY KEY (id_categoria),
    CONSTRAINT uk_t_categoria_guid UNIQUE (guid)
);

CREATE INDEX ix_t_categoria_tenant ON t_categoria (tenant);

CREATE TABLE t_produto (
    id_produto     bigint GENERATED BY DEFAULT AS IDENTITY,
    ativo          boolean        NOT NULL DEFAULT true,
    deletado       boolean        NOT NULL DEFAULT false,
    guid           uuid           NOT NULL,
    tenant         uuid,
    id_categoria   bigint         NOT NULL,
    nome           varchar(255)   NOT NULL,
    descricao      varchar(1000),
    preco          numeric(38, 2) NOT NULL,
    imagem_url     varchar(255),
    disponivel     boolean        NOT NULL DEFAULT true,
    ordem_exibicao integer,
    CONSTRAINT pk_t_produto PRIMARY KEY (id_produto),
    CONSTRAINT uk_t_produto_guid UNIQUE (guid),
    CONSTRAINT fk_t_produto_categoria FOREIGN KEY (id_categoria) REFERENCES t_categoria (id_categoria)
);

CREATE INDEX ix_t_produto_tenant ON t_produto (tenant);
CREATE INDEX ix_t_produto_categoria ON t_produto (id_categoria);

CREATE TABLE t_zona_entrega (
    id_zona_entrega        bigint GENERATED BY DEFAULT AS IDENTITY,
    ativo                  boolean        NOT NULL DEFAULT true,
    deletado               boolean        NOT NULL DEFAULT false,
    guid                   uuid           NOT NULL,
    tenant                 uuid,
    bairro                 varchar(255)   NOT NULL,
    taxa                   numeric(38, 2) NOT NULL,
    tempo_estimado_minutos integer,
    CONSTRAINT pk_t_zona_entrega PRIMARY KEY (id_zona_entrega),
    CONSTRAINT uk_t_zona_entrega_guid UNIQUE (guid)
);

CREATE INDEX ix_t_zona_entrega_tenant ON t_zona_entrega (tenant);

CREATE TABLE t_pedido (
    id_pedido            bigint GENERATED BY DEFAULT AS IDENTITY,
    ativo                boolean        NOT NULL DEFAULT true,
    deletado             boolean        NOT NULL DEFAULT false,
    guid                 uuid           NOT NULL,
    tenant               uuid,
    id_cliente           bigint,
    nome_cliente         varchar(255)   NOT NULL,
    telefone_cliente     varchar(255)   NOT NULL,
    tipo_entrega         varchar(255)   NOT NULL,
    status               varchar(255)   NOT NULL,
    forma_pagamento      varchar(255),
    endereco_rua         varchar(255),
    endereco_numero      varchar(255),
    endereco_complemento varchar(255),
    endereco_bairro      varchar(255),
    endereco_cidade      varchar(255),
    latitude             double precision,
    longitude            double precision,
    observacoes          varchar(255),
    subtotal             numeric(38, 2) NOT NULL,
    taxa_entrega         numeric(38, 2) NOT NULL,
    total                numeric(38, 2) NOT NULL,
    data_criacao         timestamp(0)   NOT NULL,
    data_atualizacao     timestamp(0),
    CONSTRAINT pk_t_pedido PRIMARY KEY (id_pedido),
    CONSTRAINT uk_t_pedido_guid UNIQUE (guid),
    CONSTRAINT fk_t_pedido_cliente FOREIGN KEY (id_cliente) REFERENCES s_usuario (id_usuario),
    CONSTRAINT ck_t_pedido_tipo_entrega CHECK (tipo_entrega IN ('ENTREGA', 'RETIRADA')),
    CONSTRAINT ck_t_pedido_status CHECK (status IN
        ('PENDENTE', 'CONFIRMADO', 'EM_PREPARO', 'SAIU_PARA_ENTREGA', 'ENTREGUE', 'CANCELADO'))
);

CREATE INDEX ix_t_pedido_tenant ON t_pedido (tenant, data_criacao DESC);

CREATE TABLE i_item_pedido (
    id_item_pedido bigint GENERATED BY DEFAULT AS IDENTITY,
    ativo          boolean        NOT NULL DEFAULT true,
    deletado       boolean        NOT NULL DEFAULT false,
    guid           uuid           NOT NULL,
    tenant         uuid,
    id_pedido      bigint         NOT NULL,
    id_produto     bigint         NOT NULL,
    nome_produto   varchar(255)   NOT NULL,
    quantidade     integer        NOT NULL,
    preco_unitario numeric(38, 2) NOT NULL,
    total_item     numeric(38, 2) NOT NULL,
    observacoes    varchar(255),
    CONSTRAINT pk_i_item_pedido PRIMARY KEY (id_item_pedido),
    CONSTRAINT uk_i_item_pedido_guid UNIQUE (guid),
    CONSTRAINT fk_i_item_pedido_pedido FOREIGN KEY (id_pedido) REFERENCES t_pedido (id_pedido),
    CONSTRAINT fk_i_item_pedido_produto FOREIGN KEY (id_produto) REFERENCES t_produto (id_produto)
);

CREATE INDEX ix_i_item_pedido_pedido ON i_item_pedido (id_pedido);
