-- Notificações da loja (hoje: pedidos). A leitura é por usuário e fica nas preferências dele; aqui só o histórico.
CREATE TABLE IF NOT EXISTS t_notificacao (
    id_notificacao bigint GENERATED BY DEFAULT AS IDENTITY,
    ativo          boolean      NOT NULL DEFAULT true,
    deletado       boolean      NOT NULL DEFAULT false,
    guid           uuid         NOT NULL,
    tenant         uuid,
    tipo           varchar(40)  NOT NULL,
    titulo         varchar(150) NOT NULL,
    mensagem       varchar(500),
    rota           varchar(255),
    id_pedido      bigint,
    data_criacao   timestamp(0) NOT NULL,
    CONSTRAINT pk_t_notificacao PRIMARY KEY (id_notificacao),
    CONSTRAINT uk_t_notificacao_guid UNIQUE (guid)
);

CREATE INDEX IF NOT EXISTS ix_t_notificacao_tenant ON t_notificacao (tenant, id_notificacao DESC);
CREATE INDEX IF NOT EXISTS ix_t_notificacao_pedido ON t_notificacao (id_pedido, tipo);
