-- Edição de pedido: marca de "editado" no pedido e histórico do que foi alterado em cada edição.
ALTER TABLE t_pedido ADD COLUMN IF NOT EXISTS editado boolean NOT NULL DEFAULT false;
ALTER TABLE t_pedido ADD COLUMN IF NOT EXISTS data_edicao timestamp(0);

CREATE TABLE IF NOT EXISTS t_pedido_alteracao (
    id_pedido_alteracao bigint GENERATED BY DEFAULT AS IDENTITY,
    ativo               boolean      NOT NULL DEFAULT true,
    deletado            boolean      NOT NULL DEFAULT false,
    guid                uuid         NOT NULL,
    tenant              uuid,
    id_pedido           bigint       NOT NULL,
    usuario_nome        varchar(255),
    descricoes          text         NOT NULL,
    data_criacao        timestamp(0) NOT NULL,
    CONSTRAINT pk_t_pedido_alteracao PRIMARY KEY (id_pedido_alteracao),
    CONSTRAINT uk_t_pedido_alteracao_guid UNIQUE (guid),
    CONSTRAINT fk_t_pedido_alteracao_pedido FOREIGN KEY (id_pedido) REFERENCES t_pedido (id_pedido)
);

CREATE INDEX IF NOT EXISTS ix_t_pedido_alteracao_pedido ON t_pedido_alteracao (id_pedido, id_pedido_alteracao DESC);

-- Permissão de editar pedido; quem já avança a situação dos pedidos passa a poder editar.
INSERT INTO s_permissao (guid, codigo, nome, tipo, id_pagina, ordem)
SELECT gen_random_uuid(), v.codigo, v.nome, 'ACAO', p.id_pagina, v.ordem
FROM (VALUES
    ('/admin/pedidos', 'PEDIDOS_ALTERAR', 'Editar pedido', 12),
    ('/admin/painel-pedidos', 'PAINEL_PEDIDOS_ALTERAR', 'Editar pedido pelo painel', 12)
) AS v (rota, codigo, nome, ordem)
JOIN s_pagina p ON p.rota = v.rota
WHERE NOT EXISTS (SELECT 1 FROM s_permissao x WHERE x.codigo = v.codigo);

INSERT INTO t_permissao_usuario (guid, tenant, id_perfil_usuario, id_permissao)
SELECT gen_random_uuid(), pu.tenant, pu.id_perfil_usuario, novo.id_permissao
FROM t_permissao_usuario pu
JOIN s_permissao atual ON atual.id_permissao = pu.id_permissao
    AND atual.codigo IN ('PEDIDOS_ALTERAR_STATUS', 'PAINEL_PEDIDOS_ALTERAR_STATUS')
JOIN s_permissao novo ON novo.codigo = replace(atual.codigo, 'ALTERAR_STATUS', 'ALTERAR')
WHERE NOT EXISTS (SELECT 1 FROM t_permissao_usuario x
                  WHERE x.id_perfil_usuario = pu.id_perfil_usuario AND x.id_permissao = novo.id_permissao);

-- Escala: as consultas de todo dia (quadro, lista por período, histórico do cliente) filtram sempre por loja.
CREATE INDEX IF NOT EXISTS ix_t_pedido_tenant_status_data ON t_pedido (tenant, status, data_criacao) WHERE deletado = false;
CREATE INDEX IF NOT EXISTS ix_t_pedido_tenant_data ON t_pedido (tenant, data_criacao DESC) WHERE deletado = false;
CREATE INDEX IF NOT EXISTS ix_t_pedido_tenant_telefone ON t_pedido (tenant, telefone_cliente) WHERE deletado = false;
CREATE INDEX IF NOT EXISTS ix_i_item_pedido_pedido ON i_item_pedido (id_pedido);
