-- Fluxo de pedidos configurável (kanban): situações (colunas) e transições (para onde cada uma pode ir) por loja.
-- categoria = significado da situação para o sistema (dashboards, notificações, relatórios): usa os valores de StatusPedido.
CREATE TABLE IF NOT EXISTS t_situacao_pedido (
    id_situacao_pedido bigint GENERATED BY DEFAULT AS IDENTITY,
    ativo              boolean      NOT NULL DEFAULT true,
    deletado           boolean      NOT NULL DEFAULT false,
    guid               uuid         NOT NULL,
    tenant             uuid,
    nome               varchar(60)  NOT NULL,
    cor                varchar(9)   NOT NULL,
    categoria          varchar(30)  NOT NULL,
    ordem              integer      NOT NULL DEFAULT 0,
    CONSTRAINT pk_t_situacao_pedido PRIMARY KEY (id_situacao_pedido),
    CONSTRAINT uk_t_situacao_pedido_guid UNIQUE (guid)
);

CREATE INDEX IF NOT EXISTS ix_t_situacao_pedido_tenant ON t_situacao_pedido (tenant, ordem) WHERE deletado = false;

CREATE TABLE IF NOT EXISTS t_transicao_pedido (
    id_transicao_pedido bigint GENERATED BY DEFAULT AS IDENTITY,
    ativo               boolean     NOT NULL DEFAULT true,
    deletado            boolean     NOT NULL DEFAULT false,
    guid                uuid        NOT NULL,
    tenant              uuid,
    id_de               bigint      NOT NULL,
    id_para             bigint      NOT NULL,
    tipo_pedido         varchar(20),
    rotulo              varchar(60),
    CONSTRAINT pk_t_transicao_pedido PRIMARY KEY (id_transicao_pedido),
    CONSTRAINT uk_t_transicao_pedido_guid UNIQUE (guid),
    CONSTRAINT fk_t_transicao_pedido_de FOREIGN KEY (id_de) REFERENCES t_situacao_pedido (id_situacao_pedido),
    CONSTRAINT fk_t_transicao_pedido_para FOREIGN KEY (id_para) REFERENCES t_situacao_pedido (id_situacao_pedido)
);

CREATE INDEX IF NOT EXISTS ix_t_transicao_pedido_tenant ON t_transicao_pedido (tenant);

-- O pedido guarda a situação atual; "status" continua existindo como a categoria dela (consultas e relatórios rápidos).
ALTER TABLE t_pedido ADD COLUMN IF NOT EXISTS id_situacao bigint;
CREATE INDEX IF NOT EXISTS ix_t_pedido_situacao ON t_pedido (tenant, id_situacao) WHERE deletado = false;

-- Loja > Fluxo de pedidos
INSERT INTO s_pagina (guid, id_categoria_menu, nome, rota, ordem, screen)
SELECT gen_random_uuid(), c.id_categoria_menu, 'Fluxo de pedidos', '/admin/fluxo-pedidos', 2, 'Loja, Fluxo de pedidos'
FROM s_categoria_menu c
WHERE c.nome = 'Loja'
  AND NOT EXISTS (SELECT 1 FROM s_pagina x WHERE x.rota = '/admin/fluxo-pedidos');

INSERT INTO s_permissao (guid, codigo, nome, tipo, id_pagina, ordem)
SELECT gen_random_uuid(), v.codigo, v.nome, v.tipo, p.id_pagina, v.ordem
FROM (VALUES
    ('FLUXO_PEDIDOS_LEITURA', 'Visualizar o fluxo de pedidos', 'LEITURA', 1),
    ('FLUXO_PEDIDOS_ESCRITA', 'Editar o fluxo de pedidos', 'ESCRITA', 2),
    ('FLUXO_PEDIDOS_ALTERAR', 'Configurar situações e transições do fluxo', 'ACAO', 3)
) AS v (codigo, nome, tipo, ordem)
JOIN s_pagina p ON p.rota = '/admin/fluxo-pedidos'
WHERE NOT EXISTS (SELECT 1 FROM s_permissao x WHERE x.codigo = v.codigo);
