-- Pagamento dividido: o pedido pode ser pago em mais de uma forma, cada uma com o seu valor, a sua taxa e, no dinheiro,
-- o valor recebido (para o troco). taxa_pagamentos é a soma das taxas e já está dentro do total do pedido.
CREATE TABLE IF NOT EXISTS t_pedido_pagamento (
    id_pedido_pagamento bigint GENERATED BY DEFAULT AS IDENTITY,
    ativo               boolean        NOT NULL DEFAULT true,
    deletado            boolean        NOT NULL DEFAULT false,
    guid                uuid           NOT NULL,
    tenant              uuid,
    id_pedido           bigint         NOT NULL,
    id_forma_pagamento  bigint,
    forma_nome          varchar(100)   NOT NULL,
    tipo                varchar(30),
    valor               numeric(10, 2) NOT NULL,
    taxa                numeric(10, 2) NOT NULL DEFAULT 0,
    valor_recebido      numeric(10, 2),
    CONSTRAINT pk_t_pedido_pagamento PRIMARY KEY (id_pedido_pagamento),
    CONSTRAINT uk_t_pedido_pagamento_guid UNIQUE (guid),
    CONSTRAINT fk_t_pedido_pagamento_pedido FOREIGN KEY (id_pedido) REFERENCES t_pedido (id_pedido)
);

CREATE INDEX IF NOT EXISTS ix_t_pedido_pagamento_pedido ON t_pedido_pagamento (id_pedido);

ALTER TABLE t_pedido ADD COLUMN IF NOT EXISTS taxa_pagamentos numeric(10, 2) NOT NULL DEFAULT 0;

-- Tempo de preparo: por produto, por categoria e um padrão da loja. O pedido guarda o prazo (o maior entre os itens).
ALTER TABLE t_produto ADD COLUMN IF NOT EXISTS tempo_preparo_minutos integer;
ALTER TABLE t_categoria ADD COLUMN IF NOT EXISTS tempo_preparo_minutos integer;
ALTER TABLE s_loja ADD COLUMN IF NOT EXISTS tempo_preparo_padrao_minutos integer NOT NULL DEFAULT 30;
ALTER TABLE t_pedido ADD COLUMN IF NOT EXISTS tempo_preparo_minutos integer;

-- Para o indicador "no prazo" do dashboard e o lembrete de atraso
CREATE INDEX IF NOT EXISTS ix_t_pedido_prazo ON t_pedido (tenant, status) WHERE deletado = false AND tempo_preparo_minutos IS NOT NULL;
