-- Entregadores da loja (próprios ou terceirizados). O token é o "segredo" do link do entregador (página do celular).
CREATE TABLE IF NOT EXISTS t_entregador (
    id_entregador      bigint GENERATED BY DEFAULT AS IDENTITY,
    ativo              boolean        NOT NULL DEFAULT true,
    deletado           boolean        NOT NULL DEFAULT false,
    guid               uuid           NOT NULL,
    tenant             uuid,
    nome               varchar(120)   NOT NULL,
    telefone           varchar(20),
    tipo               varchar(20)    NOT NULL,
    veiculo            varchar(60),
    repasse_por_entrega numeric(10, 2) NOT NULL DEFAULT 0,
    token              uuid           NOT NULL,
    ultima_latitude    double precision,
    ultima_longitude   double precision,
    posicao_em         timestamp(0),
    CONSTRAINT pk_t_entregador PRIMARY KEY (id_entregador),
    CONSTRAINT uk_t_entregador_guid UNIQUE (guid),
    CONSTRAINT uk_t_entregador_token UNIQUE (token)
);

CREATE INDEX IF NOT EXISTS ix_t_entregador_tenant ON t_entregador (tenant) WHERE deletado = false;

-- Pedido: quem entrega, quanto ele recebe pela entrega (valor no momento da atribuição) e a foto da entrega.
ALTER TABLE t_pedido ADD COLUMN IF NOT EXISTS id_entregador bigint;
ALTER TABLE t_pedido ADD COLUMN IF NOT EXISTS repasse_entregador numeric(10, 2);
ALTER TABLE t_pedido ADD COLUMN IF NOT EXISTS foto_entrega_url varchar(255);
ALTER TABLE t_pedido ADD COLUMN IF NOT EXISTS data_entrega timestamp(0);
CREATE INDEX IF NOT EXISTS ix_t_pedido_entregador ON t_pedido (tenant, id_entregador) WHERE deletado = false AND id_entregador IS NOT NULL;

-- Menu: Entrega > Entregadores e Entrega > Entregas em rota
INSERT INTO s_pagina (guid, id_categoria_menu, nome, rota, ordem, screen)
SELECT gen_random_uuid(), c.id_categoria_menu, v.nome, v.rota, v.ordem, 'Entrega, ' || v.nome
FROM s_categoria_menu c
CROSS JOIN (VALUES ('Entregadores', '/admin/entregadores', 2), ('Entregas em rota', '/admin/entregas', 3)) AS v (nome, rota, ordem)
WHERE c.nome = 'Entrega'
  AND NOT EXISTS (SELECT 1 FROM s_pagina x WHERE x.rota = v.rota);

INSERT INTO s_permissao (guid, codigo, nome, tipo, id_pagina, ordem)
SELECT gen_random_uuid(), v.codigo, v.nome, v.tipo, p.id_pagina, v.ordem
FROM (VALUES
    ('/admin/entregadores', 'ENTREGADORES_LEITURA', 'Visualizar os entregadores', 'LEITURA', 1),
    ('/admin/entregadores', 'ENTREGADORES_ESCRITA', 'Editar os entregadores', 'ESCRITA', 2),
    ('/admin/entregadores', 'ENTREGADORES_INCLUIR', 'Cadastrar entregador', 'ACAO', 3),
    ('/admin/entregadores', 'ENTREGADORES_ALTERAR', 'Alterar entregador', 'ACAO', 4),
    ('/admin/entregadores', 'ENTREGADORES_EXCLUIR', 'Excluir entregador', 'ACAO', 5),
    ('/admin/entregadores', 'ENTREGADORES_INATIVAR', 'Ativar e inativar entregadores', 'ACAO', 6),
    ('/admin/entregas', 'ENTREGAS_LEITURA', 'Visualizar as entregas em rota e o repasse', 'LEITURA', 1),
    ('/admin/entregas', 'ENTREGAS_ESCRITA', 'Editar as entregas', 'ESCRITA', 2)
) AS v (rota, codigo, nome, tipo, ordem)
JOIN s_pagina p ON p.rota = v.rota
WHERE NOT EXISTS (SELECT 1 FROM s_permissao x WHERE x.codigo = v.codigo);
