-- Conta do cliente final (entra pelo telefone com código OTP) e vínculo dos pedidos com ela.
CREATE TABLE IF NOT EXISTS s_cliente_conta (
    id_cliente_conta BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ativo            BOOLEAN      NOT NULL DEFAULT TRUE,
    deletado         BOOLEAN      NOT NULL DEFAULT FALSE,
    guid             UUID         NOT NULL,
    telefone         VARCHAR(20)  NOT NULL,
    nome             VARCHAR(120),
    data_criacao     TIMESTAMP    NOT NULL DEFAULT now(),
    ultimo_acesso    TIMESTAMP,
    CONSTRAINT uk_s_cliente_conta_guid UNIQUE (guid),
    CONSTRAINT uk_s_cliente_conta_telefone UNIQUE (telefone)
);

-- Códigos enviados: guarda só o hash, nunca o código. Expira em minutos e tem limite de tentativas.
CREATE TABLE IF NOT EXISTS s_cliente_otp (
    id_cliente_otp BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ativo          BOOLEAN     NOT NULL DEFAULT TRUE,
    deletado       BOOLEAN     NOT NULL DEFAULT FALSE,
    guid           UUID        NOT NULL,
    telefone       VARCHAR(20) NOT NULL,
    codigo_hash    VARCHAR(64) NOT NULL,
    expira_em      TIMESTAMP   NOT NULL,
    tentativas     INT         NOT NULL DEFAULT 0,
    usado          BOOLEAN     NOT NULL DEFAULT FALSE,
    data_criacao   TIMESTAMP   NOT NULL DEFAULT now(),
    CONSTRAINT uk_s_cliente_otp_guid UNIQUE (guid)
);
CREATE INDEX IF NOT EXISTS ix_s_cliente_otp_telefone ON s_cliente_otp (telefone, data_criacao DESC);

ALTER TABLE t_pedido ADD COLUMN IF NOT EXISTS id_cliente_conta BIGINT;
CREATE INDEX IF NOT EXISTS ix_t_pedido_cliente_conta ON t_pedido (id_cliente_conta, tenant);
