-- Cupons de desconto da loja e o registro de cada uso.
CREATE TABLE IF NOT EXISTS t_cupom (
    id_cupom            bigint GENERATED BY DEFAULT AS IDENTITY,
    ativo               boolean        NOT NULL DEFAULT true,
    deletado            boolean        NOT NULL DEFAULT false,
    guid                uuid           NOT NULL,
    tenant              uuid,
    codigo              varchar(40)    NOT NULL,
    descricao           varchar(200),
    tipo                varchar(20)    NOT NULL,
    valor               numeric(10, 2) NOT NULL DEFAULT 0,
    valor_minimo        numeric(10, 2),
    desconto_maximo     numeric(10, 2),
    inicio              timestamp,
    fim                 timestamp,
    limite_total        integer,
    limite_por_cliente  integer,
    primeiro_pedido     boolean        NOT NULL DEFAULT false,
    tipo_entrega        varchar(20),
    id_categoria        bigint,
    cumulativo          boolean        NOT NULL DEFAULT true,
    CONSTRAINT pk_t_cupom PRIMARY KEY (id_cupom),
    CONSTRAINT uk_t_cupom_guid UNIQUE (guid),
    CONSTRAINT ck_t_cupom_tipo CHECK (tipo IN ('PERCENTUAL', 'VALOR', 'FRETE_GRATIS'))
);

CREATE INDEX IF NOT EXISTS ix_t_cupom_tenant_codigo ON t_cupom (tenant, codigo);

CREATE TABLE IF NOT EXISTS t_cupom_uso (
    id_cupom_uso     bigint GENERATED BY DEFAULT AS IDENTITY,
    ativo            boolean        NOT NULL DEFAULT true,
    deletado         boolean        NOT NULL DEFAULT false,
    guid             uuid           NOT NULL,
    tenant           uuid,
    id_cupom         bigint         NOT NULL,
    id_pedido        bigint         NOT NULL,
    id_cliente_conta bigint,
    valor_desconto   numeric(10, 2) NOT NULL,
    data_uso         timestamp      NOT NULL DEFAULT now(),
    CONSTRAINT pk_t_cupom_uso PRIMARY KEY (id_cupom_uso),
    CONSTRAINT uk_t_cupom_uso_guid UNIQUE (guid)
);

CREATE INDEX IF NOT EXISTS ix_t_cupom_uso_cupom ON t_cupom_uso (id_cupom, id_cliente_conta);

ALTER TABLE t_pedido ADD COLUMN IF NOT EXISTS codigo_cupom varchar(40);

-- Geral > Cupons
INSERT INTO s_pagina (guid, id_categoria_menu, nome, rota, ordem, screen)
SELECT gen_random_uuid(), c.id_categoria_menu, 'Cupons', '/admin/cupons', 5, 'Geral, Cupons'
FROM s_categoria_menu c
WHERE c.nome = 'Geral'
  AND NOT EXISTS (SELECT 1 FROM s_pagina x WHERE x.rota = '/admin/cupons');

INSERT INTO s_permissao (guid, codigo, nome, tipo, id_pagina, ordem)
SELECT gen_random_uuid(), v.codigo, v.nome, v.tipo, p.id_pagina, v.ordem
FROM (VALUES
    ('/admin/cupons', 'CUPONS_LEITURA', 'Visualizar os cupons', 'LEITURA', 1),
    ('/admin/cupons', 'CUPONS_ESCRITA', 'Editar os cupons', 'ESCRITA', 2),
    ('/admin/cupons', 'CUPONS_INCLUIR', 'Cadastrar cupom', 'ACAO', 3),
    ('/admin/cupons', 'CUPONS_ALTERAR', 'Alterar cupom', 'ACAO', 4),
    ('/admin/cupons', 'CUPONS_EXCLUIR', 'Excluir cupom', 'ACAO', 5),
    ('/admin/cupons', 'CUPONS_INATIVAR', 'Ativar e inativar cupons', 'ACAO', 6)
) AS v (rota, codigo, nome, tipo, ordem)
JOIN s_pagina p ON p.rota = v.rota
WHERE NOT EXISTS (SELECT 1 FROM s_permissao x WHERE x.codigo = v.codigo);
