-- Trajeto do entregador (pontos do GPS enquanto o pedido está em rota) e código de entrega (prova de entrega).
CREATE TABLE IF NOT EXISTS t_pedido_trilha (
    id_pedido_trilha bigint GENERATED BY DEFAULT AS IDENTITY,
    ativo            boolean   NOT NULL DEFAULT true,
    deletado         boolean   NOT NULL DEFAULT false,
    guid             uuid      NOT NULL,
    tenant           uuid,
    id_pedido        bigint    NOT NULL,
    latitude         double precision NOT NULL,
    longitude        double precision NOT NULL,
    registrado_em    timestamp NOT NULL DEFAULT now(),
    CONSTRAINT pk_t_pedido_trilha PRIMARY KEY (id_pedido_trilha),
    CONSTRAINT uk_t_pedido_trilha_guid UNIQUE (guid)
);
CREATE INDEX IF NOT EXISTS ix_t_pedido_trilha_pedido ON t_pedido_trilha (id_pedido, registrado_em);

ALTER TABLE t_pedido ADD COLUMN IF NOT EXISTS codigo_entrega varchar(4);
