-- Assinaturas de notificação push (Web Push): entregador (nova entrega) e cliente acompanhando um pedido (mudança de situação).
CREATE TABLE IF NOT EXISTS t_push_assinatura (
    id_push_assinatura bigint GENERATED BY DEFAULT AS IDENTITY,
    ativo              boolean       NOT NULL DEFAULT true,
    deletado           boolean       NOT NULL DEFAULT false,
    guid               uuid          NOT NULL,
    tenant             uuid,
    tipo               varchar(20)   NOT NULL,
    id_entregador      bigint,
    id_pedido          bigint,
    endpoint           varchar(1000) NOT NULL,
    chave_p256dh       varchar(200)  NOT NULL,
    chave_auth         varchar(100)  NOT NULL,
    criado_em          timestamp     NOT NULL DEFAULT now(),
    CONSTRAINT pk_t_push_assinatura PRIMARY KEY (id_push_assinatura),
    CONSTRAINT uk_t_push_assinatura_guid UNIQUE (guid),
    CONSTRAINT ck_t_push_assinatura_tipo CHECK (tipo IN ('ENTREGADOR', 'PEDIDO'))
);
CREATE INDEX IF NOT EXISTS ix_t_push_entregador ON t_push_assinatura (id_entregador) WHERE id_entregador IS NOT NULL;
CREATE INDEX IF NOT EXISTS ix_t_push_pedido ON t_push_assinatura (id_pedido) WHERE id_pedido IS NOT NULL;
CREATE UNIQUE INDEX IF NOT EXISTS uk_t_push_endpoint_alvo ON t_push_assinatura (endpoint, tipo, coalesce(id_entregador, 0), coalesce(id_pedido, 0));
