-- Avaliação do pedido pelo cliente (nota da loja, nota da entrega e comentário) e a resposta da loja.
CREATE TABLE IF NOT EXISTS t_avaliacao (
    id_avaliacao     bigint GENERATED BY DEFAULT AS IDENTITY,
    ativo            boolean       NOT NULL DEFAULT true,
    deletado         boolean       NOT NULL DEFAULT false,
    guid             uuid          NOT NULL,
    tenant           uuid,
    id_pedido        bigint        NOT NULL,
    id_cliente_conta bigint,
    nota_loja        smallint      NOT NULL,
    nota_entrega     smallint,
    comentario       varchar(500),
    criado_em        timestamp     NOT NULL DEFAULT now(),
    resposta         varchar(500),
    respondida_em    timestamp,
    CONSTRAINT pk_t_avaliacao PRIMARY KEY (id_avaliacao),
    CONSTRAINT uk_t_avaliacao_guid UNIQUE (guid),
    CONSTRAINT uk_t_avaliacao_pedido UNIQUE (id_pedido),
    CONSTRAINT ck_t_avaliacao_nota_loja CHECK (nota_loja BETWEEN 1 AND 5),
    CONSTRAINT ck_t_avaliacao_nota_entrega CHECK (nota_entrega IS NULL OR nota_entrega BETWEEN 1 AND 5)
);
CREATE INDEX IF NOT EXISTS ix_t_avaliacao_tenant ON t_avaliacao (tenant, criado_em DESC);

-- Operação > Avaliações
INSERT INTO s_pagina (guid, id_categoria_menu, nome, rota, ordem, screen)
SELECT gen_random_uuid(), c.id_categoria_menu, 'Avaliações', '/admin/avaliacoes', 9, 'Operação, Avaliações'
FROM s_categoria_menu c
WHERE c.nome = 'Operação'
  AND NOT EXISTS (SELECT 1 FROM s_pagina x WHERE x.rota = '/admin/avaliacoes');

INSERT INTO s_permissao (guid, codigo, nome, tipo, id_pagina, ordem)
SELECT gen_random_uuid(), v.codigo, v.nome, v.tipo, p.id_pagina, v.ordem
FROM (VALUES
    ('/admin/avaliacoes', 'AVALIACOES_LEITURA', 'Visualizar as avaliações', 'LEITURA', 1),
    ('/admin/avaliacoes', 'AVALIACOES_ESCRITA', 'Editar as avaliações', 'ESCRITA', 2),
    ('/admin/avaliacoes', 'AVALIACOES_RESPONDER', 'Responder avaliações', 'ACAO', 3)
) AS v (rota, codigo, nome, tipo, ordem)
JOIN s_pagina p ON p.rota = v.rota
WHERE NOT EXISTS (SELECT 1 FROM s_permissao x WHERE x.codigo = v.codigo);
