-- Endereços salvos na conta do cliente (casa, trabalho...): escolhidos no checkout sem digitar de novo.
CREATE TABLE IF NOT EXISTS s_cliente_endereco (
    id_cliente_endereco bigint GENERATED BY DEFAULT AS IDENTITY,
    ativo               boolean          NOT NULL DEFAULT true,
    deletado            boolean          NOT NULL DEFAULT false,
    guid                uuid             NOT NULL,
    id_cliente_conta    bigint           NOT NULL,
    apelido             varchar(40)      NOT NULL,
    cep                 varchar(9),
    rua                 varchar(255)     NOT NULL,
    numero              varchar(20)      NOT NULL,
    complemento         varchar(100),
    bairro              varchar(120)     NOT NULL,
    cidade              varchar(120),
    latitude            double precision,
    longitude           double precision,
    criado_em           timestamp        NOT NULL DEFAULT now(),
    CONSTRAINT pk_s_cliente_endereco PRIMARY KEY (id_cliente_endereco),
    CONSTRAINT uk_s_cliente_endereco_guid UNIQUE (guid)
);
CREATE INDEX IF NOT EXISTS ix_s_cliente_endereco_conta ON s_cliente_endereco (id_cliente_conta) WHERE deletado = false;
