-- Fidelidade / cashback: configuração por loja e o extrato (lotes de cashback com validade) de cada cliente.
CREATE TABLE IF NOT EXISTS t_fidelidade_config (
    id_fidelidade_config bigint GENERATED BY DEFAULT AS IDENTITY,
    ativo                boolean        NOT NULL DEFAULT true,
    deletado             boolean        NOT NULL DEFAULT false,
    guid                 uuid           NOT NULL,
    tenant               uuid           NOT NULL,
    programa_ativo       boolean        NOT NULL DEFAULT false,
    percentual           numeric(5, 2)  NOT NULL DEFAULT 5,
    validade_dias        integer        NOT NULL DEFAULT 90,
    resgate_minimo       numeric(10, 2) NOT NULL DEFAULT 0,
    resgate_maximo_pct   numeric(5, 2)  NOT NULL DEFAULT 50,
    CONSTRAINT pk_t_fidelidade_config PRIMARY KEY (id_fidelidade_config),
    CONSTRAINT uk_t_fidelidade_config_guid UNIQUE (guid),
    CONSTRAINT uk_t_fidelidade_config_tenant UNIQUE (tenant)
);

-- GANHO = um lote de cashback (valor, o que ainda resta e quando vence); RESGATE/ESTORNO registram o uso no extrato.
CREATE TABLE IF NOT EXISTS t_fidelidade_movimento (
    id_fidelidade_movimento bigint GENERATED BY DEFAULT AS IDENTITY,
    ativo            boolean        NOT NULL DEFAULT true,
    deletado         boolean        NOT NULL DEFAULT false,
    guid             uuid           NOT NULL,
    tenant           uuid           NOT NULL,
    id_cliente_conta bigint         NOT NULL,
    tipo             varchar(12)    NOT NULL,
    valor            numeric(10, 2) NOT NULL,
    restante         numeric(10, 2) NOT NULL DEFAULT 0,
    expira_em        timestamp,
    id_pedido        bigint,
    criado_em        timestamp      NOT NULL DEFAULT now(),
    CONSTRAINT pk_t_fidelidade_movimento PRIMARY KEY (id_fidelidade_movimento),
    CONSTRAINT uk_t_fidelidade_movimento_guid UNIQUE (guid),
    CONSTRAINT ck_t_fidelidade_movimento_tipo CHECK (tipo IN ('GANHO', 'RESGATE', 'ESTORNO'))
);
CREATE INDEX IF NOT EXISTS ix_t_fidelidade_mov_conta ON t_fidelidade_movimento (tenant, id_cliente_conta, criado_em DESC);
CREATE UNIQUE INDEX IF NOT EXISTS uk_t_fidelidade_ganho_pedido ON t_fidelidade_movimento (id_pedido) WHERE tipo = 'GANHO' AND id_pedido IS NOT NULL;

ALTER TABLE t_pedido ADD COLUMN IF NOT EXISTS cashback_usado numeric(10, 2) NOT NULL DEFAULT 0;

-- Loja > Fidelidade
INSERT INTO s_pagina (guid, id_categoria_menu, nome, rota, ordem, screen)
SELECT gen_random_uuid(), c.id_categoria_menu, 'Fidelidade', '/admin/fidelidade', 9, 'Loja, Fidelidade'
FROM s_categoria_menu c
WHERE c.nome = 'Loja'
  AND NOT EXISTS (SELECT 1 FROM s_pagina x WHERE x.rota = '/admin/fidelidade');

INSERT INTO s_permissao (guid, codigo, nome, tipo, id_pagina, ordem)
SELECT gen_random_uuid(), v.codigo, v.nome, v.tipo, p.id_pagina, v.ordem
FROM (VALUES
    ('/admin/fidelidade', 'FIDELIDADE_LEITURA', 'Visualizar o programa de fidelidade', 'LEITURA', 1),
    ('/admin/fidelidade', 'FIDELIDADE_ESCRITA', 'Editar o programa de fidelidade', 'ESCRITA', 2),
    ('/admin/fidelidade', 'FIDELIDADE_ALTERAR', 'Alterar a configuração do programa de fidelidade', 'ACAO', 3)
) AS v (rota, codigo, nome, tipo, ordem)
JOIN s_pagina p ON p.rota = v.rota
WHERE NOT EXISTS (SELECT 1 FROM s_permissao x WHERE x.codigo = v.codigo);
