-- Site da loja (cardápio online): identidade visual, textos, redes sociais e domínio próprio.
CREATE TABLE IF NOT EXISTS t_loja_site (
    id_loja_site   bigint GENERATED BY DEFAULT AS IDENTITY,
    ativo          boolean       NOT NULL DEFAULT true,
    deletado       boolean       NOT NULL DEFAULT false,
    guid           uuid          NOT NULL,
    tenant         uuid          NOT NULL,
    cor_primaria   varchar(7),
    banner_url     varchar(255),
    sobre          varchar(1000),
    instagram      varchar(100),
    facebook       varchar(100),
    whatsapp       varchar(20),
    mensagem_topo  varchar(160),
    dominio        varchar(120),
    CONSTRAINT pk_t_loja_site PRIMARY KEY (id_loja_site),
    CONSTRAINT uk_t_loja_site_guid UNIQUE (guid),
    CONSTRAINT uk_t_loja_site_tenant UNIQUE (tenant)
);
CREATE UNIQUE INDEX IF NOT EXISTS uk_t_loja_site_dominio ON t_loja_site (lower(dominio)) WHERE dominio IS NOT NULL AND deletado = false;

-- Loja > Site
INSERT INTO s_pagina (guid, id_categoria_menu, nome, rota, ordem, screen)
SELECT gen_random_uuid(), c.id_categoria_menu, 'Site', '/admin/site', 10, 'Loja, Site'
FROM s_categoria_menu c
WHERE c.nome = 'Loja'
  AND NOT EXISTS (SELECT 1 FROM s_pagina x WHERE x.rota = '/admin/site');

INSERT INTO s_permissao (guid, codigo, nome, tipo, id_pagina, ordem)
SELECT gen_random_uuid(), v.codigo, v.nome, v.tipo, p.id_pagina, v.ordem
FROM (VALUES
    ('/admin/site', 'SITE_LEITURA', 'Visualizar o site da loja', 'LEITURA', 1),
    ('/admin/site', 'SITE_ESCRITA', 'Editar o site da loja', 'ESCRITA', 2),
    ('/admin/site', 'SITE_ALTERAR', 'Alterar o site da loja', 'ACAO', 3)
) AS v (rota, codigo, nome, tipo, ordem)
JOIN s_pagina p ON p.rota = v.rota
WHERE NOT EXISTS (SELECT 1 FROM s_permissao x WHERE x.codigo = v.codigo);
