-- Adicionais e variações: grupos de opções reutilizáveis (tamanho, adicionais, ponto da carne...) ligados aos produtos.
CREATE TABLE IF NOT EXISTS t_grupo_opcao (
    id_grupo_opcao bigint GENERATED BY DEFAULT AS IDENTITY,
    ativo          boolean      NOT NULL DEFAULT true,
    deletado       boolean      NOT NULL DEFAULT false,
    guid           uuid         NOT NULL,
    tenant         uuid,
    nome           varchar(100) NOT NULL,
    descricao      varchar(200),
    minimo         integer      NOT NULL DEFAULT 0,
    maximo         integer      NOT NULL DEFAULT 1,
    ordem          integer      NOT NULL DEFAULT 0,
    CONSTRAINT pk_t_grupo_opcao PRIMARY KEY (id_grupo_opcao),
    CONSTRAINT uk_t_grupo_opcao_guid UNIQUE (guid),
    CONSTRAINT ck_t_grupo_opcao_faixa CHECK (minimo >= 0 AND maximo >= 1 AND minimo <= maximo)
);
CREATE INDEX IF NOT EXISTS ix_t_grupo_opcao_tenant ON t_grupo_opcao (tenant);

CREATE TABLE IF NOT EXISTS t_opcao (
    id_opcao       bigint GENERATED BY DEFAULT AS IDENTITY,
    ativo          boolean        NOT NULL DEFAULT true,
    deletado       boolean        NOT NULL DEFAULT false,
    guid           uuid           NOT NULL,
    tenant         uuid,
    id_grupo_opcao bigint         NOT NULL,
    nome           varchar(100)   NOT NULL,
    preco          numeric(10, 2) NOT NULL DEFAULT 0,
    disponivel     boolean        NOT NULL DEFAULT true,
    ordem          integer        NOT NULL DEFAULT 0,
    CONSTRAINT pk_t_opcao PRIMARY KEY (id_opcao),
    CONSTRAINT uk_t_opcao_guid UNIQUE (guid),
    CONSTRAINT fk_t_opcao_grupo FOREIGN KEY (id_grupo_opcao) REFERENCES t_grupo_opcao (id_grupo_opcao)
);
CREATE INDEX IF NOT EXISTS ix_t_opcao_grupo ON t_opcao (id_grupo_opcao);

CREATE TABLE IF NOT EXISTS t_produto_grupo (
    id_produto_grupo bigint GENERATED BY DEFAULT AS IDENTITY,
    ativo            boolean NOT NULL DEFAULT true,
    deletado         boolean NOT NULL DEFAULT false,
    guid             uuid    NOT NULL,
    tenant           uuid,
    id_produto       bigint  NOT NULL,
    id_grupo_opcao   bigint  NOT NULL,
    ordem            integer NOT NULL DEFAULT 0,
    CONSTRAINT pk_t_produto_grupo PRIMARY KEY (id_produto_grupo),
    CONSTRAINT uk_t_produto_grupo_guid UNIQUE (guid),
    CONSTRAINT uk_t_produto_grupo_par UNIQUE (id_produto, id_grupo_opcao),
    CONSTRAINT fk_t_produto_grupo_produto FOREIGN KEY (id_produto) REFERENCES t_produto (id_produto),
    CONSTRAINT fk_t_produto_grupo_grupo FOREIGN KEY (id_grupo_opcao) REFERENCES t_grupo_opcao (id_grupo_opcao)
);
CREATE INDEX IF NOT EXISTS ix_t_produto_grupo_produto ON t_produto_grupo (id_produto);

-- O que o cliente escolheu em cada item do pedido (nome e preço no momento da compra).
CREATE TABLE IF NOT EXISTS i_item_pedido_opcao (
    id_item_pedido_opcao bigint GENERATED BY DEFAULT AS IDENTITY,
    ativo                boolean        NOT NULL DEFAULT true,
    deletado             boolean        NOT NULL DEFAULT false,
    guid                 uuid           NOT NULL,
    tenant               uuid,
    id_item_pedido       bigint         NOT NULL,
    id_opcao             bigint,
    nome_grupo           varchar(100)   NOT NULL,
    nome_opcao           varchar(100)   NOT NULL,
    preco                numeric(10, 2) NOT NULL DEFAULT 0,
    CONSTRAINT pk_i_item_pedido_opcao PRIMARY KEY (id_item_pedido_opcao),
    CONSTRAINT uk_i_item_pedido_opcao_guid UNIQUE (guid),
    CONSTRAINT fk_i_item_pedido_opcao_item FOREIGN KEY (id_item_pedido) REFERENCES i_item_pedido (id_item_pedido)
);
CREATE INDEX IF NOT EXISTS ix_i_item_pedido_opcao_item ON i_item_pedido_opcao (id_item_pedido);

-- Cardápio > Adicionais e variações
INSERT INTO s_pagina (guid, id_categoria_menu, nome, rota, ordem, screen)
SELECT gen_random_uuid(), c.id_categoria_menu, 'Adicionais e variações', '/admin/grupos-opcao', 8, 'Cardápio, Adicionais e variações'
FROM s_categoria_menu c
WHERE c.nome = 'Cardápio'
  AND NOT EXISTS (SELECT 1 FROM s_pagina x WHERE x.rota = '/admin/grupos-opcao');

INSERT INTO s_permissao (guid, codigo, nome, tipo, id_pagina, ordem)
SELECT gen_random_uuid(), v.codigo, v.nome, v.tipo, p.id_pagina, v.ordem
FROM (VALUES
    ('/admin/grupos-opcao', 'GRUPOS_OPCAO_LEITURA', 'Visualizar adicionais e variações', 'LEITURA', 1),
    ('/admin/grupos-opcao', 'GRUPOS_OPCAO_ESCRITA', 'Editar adicionais e variações', 'ESCRITA', 2),
    ('/admin/grupos-opcao', 'GRUPOS_OPCAO_INCLUIR', 'Cadastrar grupo de opções', 'ACAO', 3),
    ('/admin/grupos-opcao', 'GRUPOS_OPCAO_ALTERAR', 'Alterar grupo de opções', 'ACAO', 4),
    ('/admin/grupos-opcao', 'GRUPOS_OPCAO_EXCLUIR', 'Excluir grupo de opções', 'ACAO', 5),
    ('/admin/grupos-opcao', 'GRUPOS_OPCAO_INATIVAR', 'Ativar e inativar grupos de opções', 'ACAO', 6)
) AS v (rota, codigo, nome, tipo, ordem)
JOIN s_pagina p ON p.rota = v.rota
WHERE NOT EXISTS (SELECT 1 FROM s_permissao x WHERE x.codigo = v.codigo);
