-- Estoque de ingredientes: saldo, mínimo e histórico de movimentos (entrada, baixa por pedido, perda, ajuste, estorno).
ALTER TABLE t_produto ADD COLUMN IF NOT EXISTS controla_estoque boolean       NOT NULL DEFAULT false;
ALTER TABLE t_produto ADD COLUMN IF NOT EXISTS estoque_atual    numeric(14, 3) NOT NULL DEFAULT 0;
ALTER TABLE t_produto ADD COLUMN IF NOT EXISTS estoque_minimo   numeric(14, 3) NOT NULL DEFAULT 0;

CREATE TABLE IF NOT EXISTS t_movimento_estoque (
    id_movimento_estoque bigint GENERATED BY DEFAULT AS IDENTITY,
    ativo          boolean        NOT NULL DEFAULT true,
    deletado       boolean        NOT NULL DEFAULT false,
    guid           uuid           NOT NULL,
    tenant         uuid,
    id_ingrediente bigint         NOT NULL,
    tipo           varchar(20)    NOT NULL,
    quantidade     numeric(14, 3) NOT NULL,
    saldo_apos     numeric(14, 3) NOT NULL,
    motivo         varchar(200),
    id_pedido      bigint,
    data_hora      timestamp      NOT NULL,
    CONSTRAINT pk_t_movimento_estoque PRIMARY KEY (id_movimento_estoque),
    CONSTRAINT uk_t_movimento_estoque_guid UNIQUE (guid),
    CONSTRAINT fk_t_movimento_estoque_ingrediente FOREIGN KEY (id_ingrediente) REFERENCES t_produto (id_produto)
);
CREATE INDEX IF NOT EXISTS ix_t_movimento_estoque_ingrediente ON t_movimento_estoque (id_ingrediente, data_hora DESC);
CREATE INDEX IF NOT EXISTS ix_t_movimento_estoque_pedido ON t_movimento_estoque (id_pedido);

-- Cardápio > Estoque e Loja > Divulgação
INSERT INTO s_pagina (guid, id_categoria_menu, nome, rota, ordem, screen)
SELECT gen_random_uuid(), c.id_categoria_menu, 'Estoque', '/admin/estoque', 30, 'Cardápio, Estoque'
FROM s_categoria_menu c
WHERE c.nome = 'Cardápio'
  AND NOT EXISTS (SELECT 1 FROM s_pagina x WHERE x.rota = '/admin/estoque');

INSERT INTO s_pagina (guid, id_categoria_menu, nome, rota, ordem, screen)
SELECT gen_random_uuid(), c.id_categoria_menu, 'Divulgação', '/admin/divulgacao', 20, 'Loja, Divulgação'
FROM s_categoria_menu c
WHERE c.nome = 'Loja'
  AND NOT EXISTS (SELECT 1 FROM s_pagina x WHERE x.rota = '/admin/divulgacao');

INSERT INTO s_permissao (guid, codigo, nome, tipo, id_pagina, ordem)
SELECT gen_random_uuid(), v.codigo, v.nome, v.tipo, p.id_pagina, v.ordem
FROM (VALUES
    ('/admin/estoque', 'ESTOQUE_LEITURA', 'Visualizar o estoque de ingredientes', 'LEITURA', 1),
    ('/admin/estoque', 'ESTOQUE_ESCRITA', 'Lançar movimentos de estoque', 'ESCRITA', 2),
    ('/admin/estoque', 'ESTOQUE_ALTERAR', 'Alterar controle e mínimo do estoque', 'ACAO', 3),
    ('/admin/divulgacao', 'DIVULGACAO_LEITURA', 'Visualizar o material de divulgação', 'LEITURA', 1)
) AS v (rota, codigo, nome, tipo, ordem)
JOIN s_pagina p ON p.rota = v.rota
WHERE NOT EXISTS (SELECT 1 FROM s_permissao x WHERE x.codigo = v.codigo);
