-- Funcionarios (t_funcionario), dados completos da pessoa fisica, endereco, contatos,
-- foto do usuario e opcoes adicionais do usuario na loja.

-- 1) Pessoa fisica: novos campos (o telefone passa a ser um contato em t_pessoa_telefone)
ALTER TABLE t_pessoa_fisica ADD COLUMN IF NOT EXISTS sexo varchar(255);
ALTER TABLE t_pessoa_fisica ADD COLUMN IF NOT EXISTS rg varchar(30);
ALTER TABLE t_pessoa_fisica ADD COLUMN IF NOT EXISTS naturalidade varchar(255);
ALTER TABLE t_pessoa_fisica ADD COLUMN IF NOT EXISTS nacionalidade varchar(255);
ALTER TABLE t_pessoa_fisica ADD COLUMN IF NOT EXISTS estado_civil varchar(255);
ALTER TABLE t_pessoa_fisica ADD COLUMN IF NOT EXISTS profissao varchar(255);
ALTER TABLE t_pessoa_fisica ADD COLUMN IF NOT EXISTS observacao varchar(2000);
ALTER TABLE t_pessoa_fisica DROP COLUMN IF EXISTS telefone;

ALTER TABLE t_pessoa_fisica DROP CONSTRAINT IF EXISTS ck_t_pessoa_fisica_sexo;
ALTER TABLE t_pessoa_fisica ADD CONSTRAINT ck_t_pessoa_fisica_sexo
    CHECK (sexo IS NULL OR sexo IN ('MASCULINO', 'FEMININO', 'OUTRO'));
ALTER TABLE t_pessoa_fisica DROP CONSTRAINT IF EXISTS ck_t_pessoa_fisica_estado_civil;
ALTER TABLE t_pessoa_fisica ADD CONSTRAINT ck_t_pessoa_fisica_estado_civil
    CHECK (estado_civil IS NULL OR estado_civil IN
        ('SOLTEIRO', 'CASADO', 'SEPARADO', 'DIVORCIADO', 'VIUVO', 'UNIAO_ESTAVEL'));

-- um CPF por loja (so digitos)
CREATE UNIQUE INDEX IF NOT EXISTS uk_t_pessoa_fisica_tenant_cpf
    ON t_pessoa_fisica (tenant, cpf) WHERE cpf IS NOT NULL AND deletado = false;

-- 2) Endereco (um por pessoa) e contatos
CREATE TABLE IF NOT EXISTS t_pessoa_endereco (
    id_pessoa_endereco bigint GENERATED BY DEFAULT AS IDENTITY,
    ativo              boolean      NOT NULL DEFAULT true,
    deletado           boolean      NOT NULL DEFAULT false,
    guid               uuid         NOT NULL,
    tenant             uuid,
    id_pessoa          bigint       NOT NULL,
    cep                varchar(9),
    logradouro         varchar(255),
    numero             varchar(20),
    complemento        varchar(255),
    bairro             varchar(255),
    cidade             varchar(255),
    estado             varchar(2),
    CONSTRAINT pk_t_pessoa_endereco PRIMARY KEY (id_pessoa_endereco),
    CONSTRAINT uk_t_pessoa_endereco_guid UNIQUE (guid),
    CONSTRAINT uk_t_pessoa_endereco_pessoa UNIQUE (id_pessoa),
    CONSTRAINT fk_t_pessoa_endereco_pessoa FOREIGN KEY (id_pessoa) REFERENCES t_pessoa (id_pessoa)
);

CREATE TABLE IF NOT EXISTS t_pessoa_telefone (
    id_pessoa_telefone bigint GENERATED BY DEFAULT AS IDENTITY,
    ativo              boolean      NOT NULL DEFAULT true,
    deletado           boolean      NOT NULL DEFAULT false,
    guid               uuid         NOT NULL,
    tenant             uuid,
    id_pessoa          bigint       NOT NULL,
    tipo               varchar(255) NOT NULL,
    numero             varchar(20)  NOT NULL,
    observacao         varchar(255),
    CONSTRAINT pk_t_pessoa_telefone PRIMARY KEY (id_pessoa_telefone),
    CONSTRAINT uk_t_pessoa_telefone_guid UNIQUE (guid),
    CONSTRAINT fk_t_pessoa_telefone_pessoa FOREIGN KEY (id_pessoa) REFERENCES t_pessoa (id_pessoa),
    CONSTRAINT ck_t_pessoa_telefone_tipo CHECK (tipo IN ('COMERCIAL', 'RESIDENCIAL', 'CELULAR', 'OUTRO'))
);

CREATE INDEX IF NOT EXISTS ix_t_pessoa_telefone_pessoa ON t_pessoa_telefone (id_pessoa);

CREATE TABLE IF NOT EXISTS t_pessoa_email (
    id_pessoa_email bigint GENERATED BY DEFAULT AS IDENTITY,
    ativo           boolean      NOT NULL DEFAULT true,
    deletado        boolean      NOT NULL DEFAULT false,
    guid            uuid         NOT NULL,
    tenant          uuid,
    id_pessoa       bigint       NOT NULL,
    email           varchar(255) NOT NULL,
    observacao      varchar(255),
    CONSTRAINT pk_t_pessoa_email PRIMARY KEY (id_pessoa_email),
    CONSTRAINT uk_t_pessoa_email_guid UNIQUE (guid),
    CONSTRAINT fk_t_pessoa_email_pessoa FOREIGN KEY (id_pessoa) REFERENCES t_pessoa (id_pessoa)
);

CREATE INDEX IF NOT EXISTS ix_t_pessoa_email_pessoa ON t_pessoa_email (id_pessoa);

-- 3) Funcionario: uma pessoa da loja com dados de trabalho
CREATE TABLE IF NOT EXISTS t_funcionario (
    id_funcionario  bigint GENERATED BY DEFAULT AS IDENTITY,
    ativo           boolean      NOT NULL DEFAULT true,
    deletado        boolean      NOT NULL DEFAULT false,
    guid            uuid         NOT NULL,
    tenant          uuid,
    id_pessoa       bigint       NOT NULL,
    vendedor        boolean      NOT NULL DEFAULT false,
    numero_cnh      varchar(20),
    vencimento_cnh  date,
    CONSTRAINT pk_t_funcionario PRIMARY KEY (id_funcionario),
    CONSTRAINT uk_t_funcionario_guid UNIQUE (guid),
    CONSTRAINT uk_t_funcionario_pessoa UNIQUE (id_pessoa),
    CONSTRAINT fk_t_funcionario_pessoa FOREIGN KEY (id_pessoa) REFERENCES t_pessoa (id_pessoa)
);

CREATE INDEX IF NOT EXISTS ix_t_funcionario_tenant ON t_funcionario (tenant);

-- Usuarios ja vinculados a uma loja passam a ter o funcionario correspondente
INSERT INTO t_funcionario (guid, tenant, id_pessoa)
SELECT gen_random_uuid(), p.tenant, p.id_pessoa
FROM t_pessoa p
WHERE p.id_pessoa_fisica IS NOT NULL
  AND EXISTS (SELECT 1 FROM t_perfil_usuario pu WHERE pu.id_pessoa = p.id_pessoa)
  AND NOT EXISTS (SELECT 1 FROM t_funcionario f WHERE f.id_pessoa = p.id_pessoa);

-- 4) Usuario na loja: opcao "Administrador" (usada pelas permissoes, implementacao futura)
ALTER TABLE t_perfil_usuario ADD COLUMN IF NOT EXISTS administrador boolean NOT NULL DEFAULT false;
UPDATE t_perfil_usuario SET administrador = true
WHERE id_perfil IN (SELECT id_perfil FROM s_perfil WHERE codigo = 'ROLE_ADMIN_LOJA');

-- 5) Foto do usuario (tabela separada para nao carregar a imagem em toda consulta de usuario)
CREATE TABLE IF NOT EXISTS s_usuario_foto (
    id_usuario_foto bigint GENERATED BY DEFAULT AS IDENTITY,
    ativo           boolean      NOT NULL DEFAULT true,
    deletado        boolean      NOT NULL DEFAULT false,
    guid            uuid         NOT NULL,
    id_usuario      bigint       NOT NULL,
    tipo_conteudo   varchar(50)  NOT NULL,
    conteudo        bytea        NOT NULL,
    CONSTRAINT pk_s_usuario_foto PRIMARY KEY (id_usuario_foto),
    CONSTRAINT uk_s_usuario_foto_guid UNIQUE (guid),
    CONSTRAINT uk_s_usuario_foto_usuario UNIQUE (id_usuario),
    CONSTRAINT fk_s_usuario_foto_usuario FOREIGN KEY (id_usuario) REFERENCES s_usuario (id_usuario)
);

-- 6) Menu: pagina Funcionarios na categoria Geral
INSERT INTO s_pagina (guid, id_categoria_menu, nome, rota, ordem)
SELECT gen_random_uuid(), c.id_categoria_menu, 'Funcionários', '/admin/funcionarios', 2
FROM s_categoria_menu c
WHERE c.nome = 'Geral'
  AND NOT EXISTS (SELECT 1 FROM s_pagina x WHERE x.rota = '/admin/funcionarios');
